# Generated by Django 6.0.2 on 2026-02-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_cotisation_employe', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Taux cotisation employé (%)')),
                ('taux_cotisation_employeur', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='Taux cotisation employeur (%)')),
                ('taux_heure_sup_normale', models.DecimalField(decimal_places=2, default=125.0, max_digits=5, verbose_name='Taux heure sup normale (% du taux horaire)')),
                ('taux_heure_sup_nuit', models.DecimalField(decimal_places=2, default=150.0, max_digits=5, verbose_name='Taux heure sup de nuit (% du taux horaire)')),
                ('taux_heure_sup_weekend', models.DecimalField(decimal_places=2, default=175.0, max_digits=5, verbose_name='Taux heure sup week-end (% du taux horaire)')),
                ('tranche1_max', models.DecimalField(decimal_places=2, default=30000, max_digits=12, verbose_name='Tranche 1 max')),
                ('tranche1_taux', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux tranche 1 (%)')),
                ('tranche2_max', models.DecimalField(decimal_places=2, default=50000, max_digits=12, verbose_name='Tranche 2 max')),
                ('tranche2_taux', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Taux tranche 2 (%)')),
                ('tranche3_max', models.DecimalField(decimal_places=2, default=80000, max_digits=12, verbose_name='Tranche 3 max')),
                ('tranche3_taux', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Taux tranche 3 (%)')),
                ('tranche4_max', models.DecimalField(decimal_places=2, default=120000, max_digits=12, verbose_name='Tranche 4 max')),
                ('tranche4_taux', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Taux tranche 4 (%)')),
                ('tranche5_taux', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Taux tranche 5 (%)')),
                ('heures_travail_mensuel', models.IntegerField(default=173, verbose_name='Heures de travail mensuel')),
                ('actif', models.BooleanField(default=True, verbose_name='Paramètre actif')),
                ('date_application', models.DateField(verbose_name="Date d'application")),
            ],
            options={
                'verbose_name': 'Paramètre de paie',
                'verbose_name_plural': 'Paramètres de paie',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='TypeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_element', models.CharField(choices=[('prime', 'Prime'), ('deduction', 'Déduction')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'élément",
                'verbose_name_plural': "Types d'éléments",
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire de base')),
                ('heures_sup_normales', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup normales')),
                ('montant_heures_sup_normales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant heures sup normales')),
                ('heures_sup_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup de nuit')),
                ('montant_heures_sup_nuit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant heures sup de nuit')),
                ('heures_sup_weekend', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Heures sup week-end')),
                ('montant_heures_sup_weekend', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant heures sup week-end')),
                ('total_primes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total primes')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total déductions')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire brut')),
                ('cotisation_sociale_employe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cotisation sociale employé')),
                ('cotisation_sociale_employeur', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cotisation sociale employeur')),
                ('salaire_imposable', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire imposable')),
                ('impot_revenu', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Impôt sur le revenu')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salaire net')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_paiement', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='gestion_emp.employe')),
                ('parametres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_paie.parametrepaie', verbose_name='Paramètres utilisés')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='ElementPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('commentaire', models.CharField(blank=True, max_length=200, verbose_name='Commentaire')),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='gestion_paie.bulletinpaie')),
                ('type_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_paie.typeelement')),
            ],
            options={
                'verbose_name': 'Élément de paie',
                'verbose_name_plural': 'Éléments de paie',
            },
        ),
    ]
