# Generated by Django 6.0.2 on 2026-02-16 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_paie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='parametres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion_paie.parametrepaie', verbose_name='Paramètres utilisés'),
        ),
    ]
