# Generated by Django 6.0.2 on 2026-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_paie', '0002_alter_bulletinpaie_parametres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='cotisation_sociale_employe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cotisation sociale employé'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='cotisation_sociale_employeur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cotisation sociale employeur'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='impot_revenu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impôt sur le revenu'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire de base'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='salaire_brut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire brut'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='salaire_imposable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire imposable'),
        ),
        migrations.AlterField(
            model_name='bulletinpaie',
            name='salaire_net',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salaire net'),
        ),
    ]
