# Generated by Django 6.0.2 on 2026-02-16 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('telephone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide', regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('poste', models.CharField(choices=[('directeur', 'Directeur'), ('manager', 'Manager'), ('chef_equipe', "Chef d'équipe"), ('employe', 'Employé'), ('stagiaire', 'Stagiaire')], max_length=50, verbose_name='Poste')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('suspendu', 'Suspendu'), ('demission', 'Démission')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['-date_embauche'],
            },
        ),
    ]
